version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vsf
    ports:
      - "5432:5432"
  api:
    build: ./api
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/vsf
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - db
  web:
    build: ./web
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - api
